### ISSUE TITLE
Reset button should be separate from the other buttons

### ISSUE THREAD

**Issue by osbock** [wyolum/mmM#1]
It's too easy to try all the buttons, and the reset looks just like another button.

**Comment by Anool** [comment]
We could use right angle switches with long actuators for the regular buttons, and a shorter stem for the RESET.
Or, we can use a horizontal switch for RESET (not right angle). But this may not be accessible from outside the case. Suggestions on how to solve this.

**Comment by osbock** [comment]
Maybe it's completely solved by the case. A recessed button (perhaps poked with a paper clip) versus exterior protruding buttons would do the trick!

**Comment by Anool** [comment]
+1. That solves it. I'm closing this issue. We can open another one regarding features that the case must have. Reset button recessed, slot for coin battery, Slots for cables etc.
